=== vce0002-create/1DAM_LMSG_vce0002/Tema 11/Ejemplo 5/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>

            
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>


                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>


                            <xs:choice>
                                <xs:element name="cilindrada" type="xs:string"></xs:element>
                                <xs:element name="caballos" type="tipocaballo"></xs:element>
                            </xs:choice>


                            <xs:element name="combustible" type="tipocombustible"></xs:element>
                            <xs:element name="precio" type="xs:string"></xs:element>
                            <xs:element name="año" type="tipoaño" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="tipodni" minOccurs="0"
                                maxOccurs="unbounded"></xs:element>
                            <xs:element name="accesorios" type="tresaccesorios" minOccurs="0"></xs:element>
                        </xs:sequence>


                        <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>


            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="tipocombustible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Gasolina"></xs:enumeration>
            <xs:enumeration value="Diesel"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocaballo">
        <xs:restriction base="xs:unsignedShort">
            <xs:minInclusive value="60"></xs:minInclusive>
            <xs:maxInclusive value="180"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>


    <!-- Año de cuatro cifras-->
    <xs:simpleType name="tipoaño">
        <xs:restriction base="xs:unsignedShort">
            <xs:totalDigits value="4"></xs:totalDigits>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="tipoaccesorio">
        <xs:list itemType="xs:string"></xs:list>
    </xs:simpleType>

    <xs:simpleType name="tresaccesorios">
        <xs:restriction base="tipoaccesorio">
            <xs:maxLength value="3"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== vce0002-create/1DAM_LMSG_vce0002/Tema 11/Ejemplo 5/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">

    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000€</precio>
        <año>2018</año>
        <color>negro</color>
        <interesado>33358697A</interesado>
        <interesado>30515455T</interesado>
        <accesorios>navegador llantas alerón</accesorios>
    </coche>

    <coche matricula="8280DGH">
        <marca>Volkwagen</marca>
        <modelo>Polo</modelo>
        <cilindrada>1.2</cilindrada>
        <combustible>Gasolina</combustible>
        <precio>5.000€</precio>
        <color>rojo</color>
        <interesado>60514553T</interesado>
    </coche>

    <coche matricula="8280DGH">
        <marca>Renault</marca>
        <modelo>Megane</modelo>
        <caballos>120</caballos>
        <combustible>Diesel</combustible>
        <precio>7.500€</precio>
        <color>verde</color>
    </coche>

</concesionario>
