=== vce0002-create/1DAM_LMSG_vce0002/Tema 11/Ejemplo 3/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="concensionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                        <xs:element name="marca" type="xs:string"></xs:element>
                        <xs:element name="modelo" type="xs:string"></xs:element>

                        <xs:choice>
                        <xs:element name="cilindrada" type="xs:decimal"></xs:element>
                        <xs:element name="caballos" type="xs:integer"></xs:element>
                        </xs:choice>
                        
                        <xs:element name="combustible" type="xs:string"></xs:element>
                        <xs:element name="precio" type="xs:string"></xs:element>
                        <xs:element name="año" type="xs:integer" minOccurs="0"></xs:element>
                        <xs:element name="color" type="xs:string"></xs:element>
                        <xs:element name="interesado" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
                        
                </xs:sequence>
                    <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
                <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vce0002-create/1DAM_LMSG_vce0002/Tema 11/Ejemplo 3/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concensionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesionario.xsd" provincia="Malaga">


<coche matricula = "6732KPC">
    <marca>Seat</marca>
    <modelo>Ateca</modelo>
    <cilindrada>1.7</cilindrada>
    <combustible>Diesel</combustible>
    <precio>23.000$</precio>
    <año>2018</año>
    <color>negro</color>
    <interesado>33358697A</interesado>
    <interesado>30515455T</interesado>
</coche>

<coche matricula = "8220DGH">
    <marca>Volkswaguen</marca>
    <modelo>Polo</modelo>
    <cilindrada>1.2</cilindrada>
    <combustible>Gasolina</combustible>
    <precio>5.000$</precio>
    <color>color</color>
    <interesado>60514553T</interesado>
</coche>

<coche matricula = "7786HHG">
    <marca>Renault</marca>
    <modelo>Megane</modelo>
    <caballos>120</caballos>
    <combustible>Diesel</combustible>
    <precio>7.500$</precio>
    <color>verde</color>
</coche>



</concensionario>
